### PR TITLE
Update README_data.md

### PR DESCRIPTION
**Pull request by kaedonkers**
- Updated available meteorological variables with new descriptions
- Updated comment on what dates of data are available

### CODE REVIEW

**Comment by kaedonkers** [comment]
@tam203 Two questions:
1. Should we remove the comment that _"At time of writing (26th May 2020) the available data is from 1st Jan - 25th May 2020."_? It seems a bit redundant, or do you think it clarifies what data is available when?
2. Do we want to add the AQ data descriptions to this README or do we want to create a new README file for AQ data?

**Comment by maria-a62** [comment]
1. My version of Readme (under latest) says "At time of writing (4th May 2020) the available data is from 1st Jan - 3rd May 2020.” So we should remove it.

2. Tricky. I would say add in the same, otherwise we have Readme 1 Readme 2? On the other hand are they under same license? Need to restructure a bit, like the database has nwp and aq data, then start describing.

**Comment by kaedonkers** [comment]
@tam203 @maria-a62 @bsherratt 
Just to let you all know that I have updated this PR with the README_data.md changes @bsherratt made in #4, since that PR is having some merging issues and we want to update the data readme asap.
@tam203 Is this ready to merge?

**Comment by tam203** [comment]
Ok I did some poor comms on all of this but I think all is merged and committed. 

There was issues caused because I changed the deploy script now that there are two buckets (open / non-commercial) . @bsherratt also changed the script so that his docs would be included and deployed. Hence a merge conflict.

I **think** that we are all ok now this is all merged in. Please @kaedonkers @maria-a62 @bsherratt have a scan of Master and maybe:

* [read me open](https://metdatasa.blob.core.windows.net/covid19-response/README_data.html)
* [read me non-commercial](https://metdatasa.blob.core.windows.net/covid19-response-non-commercial/README.html)

Thanks all!

**Comment by bsherratt** [comment]
Looks good to me.

One small thing is that due to the merge conflict, one change I made was missed - adding a `<meta charset="utf-8">` tag to the start of each generated HTML file, so browsers don't assume ASCII and render nonsense when they see unicode characters like "smart" quotes.

The other solution of course is make them regular quotes instead, and it seems like this happened in README_data.md, but not in LICENCE.txt (typo by the way, should be license) or README_non-commercial_data.md. So maybe do the same there. The meta tag does stop browsers warning in the console about unspecified encodings, but isn't an option for a plaintext file anyway.

Otherwise, good work resolving the various conflicts - was a little concerned friday afternoon when I saw how much else was going on, and travis complaining about the first attempt.

**Comment by kaedonkers** [comment]
Thanks both! Regarding unicode vs ascii, I changed the README_data.md to
include regular quotation marks in my PR
<https://github.com/informatics-lab/covid19-dataset-documentation/pull/6/files#diff-f8efadcb819bd157355c4c9a7446da30R7>.
But specifying the encoding in the HTML is a good idea too :)

K

*---------------------------------------------------------------*

*Kevin Donkers, MSci*
Technologist

Met Office Informatics Lab



www.informaticslab.co.uk

Met Office HPC Complex, Upper Richardson,

Science Park, Exeter, EX5 2FS

United Kingdom



Please send all officially sensitive info to:

kevin.donkers@metoffice.gov.uk

(and please let me know you've sent it!)

**Comment by tam203** [comment]
Sorry I missed those changes @bsherratt . If you want to open another pull request to fix I promise I won't make a merge conflict nightmare at the same time.

**Pull request merged**
